### ISSUE TITLE
Custom linters for invalid code within dataflow or foreign queries

### ISSUE THREAD

**Issue by vemv** [redplanetlabs/rama-clj-kondo#7]
Hi!

As a suggestion, it would seem feasible to create custom linters for the following patterns that are invalid code:

* anonymous functions placed within a `foreign-select` call
  * these only work in a IPC context and therefore constitute bugs that can make it pass the test suite.
* keywords used as functions within Dataflow code
  * these create a confusing exception.
 
WDYT?

Thanks - V

**Comment by basilesportif** [comment]
Would you create these linters at the editor level?

**Comment by nixin72** [comment]
Hi @vemv thanks for the suggestions! I'll create tickets for those. Building off the first point there, I think we should also have linting that Clojure primitives don't appear in Rama code (`fn`, `let`, `if` and friends). 

@basilesportif - This would be implemented as hooks to clj-kondo, so any editor using clj-kondo or Clojure LSP would benefit from these changes. VSCode, Emacs, Vim, etc. IntelliJ's Cursive doesn't use clj-kondo though, so that wouldn't get support from this.

**Comment by vemv** [comment]
Awesome, thanks!

> I think we should also have linting that Clojure primitives don't appear in Rama code

Yes, I was tempted to request that although I noticed that one gets a pretty clear compile-time error. So I requested the simplest thing first 😁

But yes, some folks tend to want feedback asap (i.e. before it hits the Clojure compiler).

>  IntelliJ's Cursive doesn't use clj-kondo though, so that wouldn't get support from this.

There's https://github.com/clojure-lsp/clojure-lsp-intellij as of lately as well!

**Comment by vemv** [comment]
Another thing that I spotted is that Java constructors are forbidden and possibly all interop IIRC?

**Comment by vemv** [comment]
>  I think we should also have linting that Clojure primitives don't appear in Rama code (fn, let, if and friends).

Yes, `and` bit me today, it's somewhat easy to forget

**Comment by nixin72** [comment]
Ahh, forgot to close this issue after I merged in the fixes.

**Comment by vemv** [comment]
Thanks! Will make sure to try these out.
